# Generated by Django 5.2.5 on 2025-08-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="adltest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campo1", models.CharField(max_length=100)),
                ("valor1", models.IntegerField()),
            ],
        ),
    ]
